#+TITLE: Readme

* Spotify Talks to a Genius
** Quick Description
An engine that searches the [[https://www.genius.com][Genius]] database for [[http://www.spotify.com][Spotify]]-playable tracks whose lyrics contain the search term.

** Background
This project began as simply a means for learning and exploration. I had been trying to find a project that would allow me to practice my Javascript/React frontend skills while utilyzing an external API. I settled on using the Spotify API because of its high-quality and the simple, familiar context (music!).

Spotify provides quite a bit of built-in functionality via its API, but it does not offer the ability to search for tracks by lyrics. I figured I could use the Genius API in conjunction with the Spotify API to create an online tool to fill this gap.

I initially expected to create an SPA, but upon further investigation into the Genius API, I realized that there was one major limitation: their API does not permit the searching of lyrics. In fact, it seems that Genius had moved from being focused on lyrics in particular to being focused on document-annotation in general. And therefore, the API revolved around annotations. (Part of the reason for this seems to be copyright-related, which has further implications for this project as well.) Without API functions to search the lyrics, I would have to scrape the html. This meant that I could not rely on an SPA structure due to CORS restrictions. So...I had to use a server-side functions to implement the html scraping.

I decided to stick with Javascript and write the server using Node. To make my life a little more difficult and learn a little more in the process, I also decided to avoid prewritten frameworks or modules such as Express and Node-Fetch. As such, you'll find less readable, less sophisticated code within, but it served my main purpose of learning.

** WIP. More to come...
